
services:
  - type: web
    name: bug-tracker-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src